name: Execution des tests cypress

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Verify cypress info
        run: npx cypress info

      - name: Run tests
        run: npx cypress run
